In [27]:
import pandas as pd
from datetime import datetime

In [14]:
df=pd.read_html("https://simple.wikipedia.org/wiki/Democratic_Party_(United_States)")[1]

In [17]:
df

,#,President,Portrait,State,Term start,Term end,Years in office
0,7,Andrew Jackson (1767–1845),NaN,Tennessee,"March 4, 1829","March 4, 1837","8 years, 0 days"
1,8,Martin Van Buren (1782–1862),NaN,New York,"March 4, 1837","March 4, 1841","4 years, 0 days"
2,11,James K. Polk (1795–1849),NaN,Tennessee,"March 4, 1845","March 4, 1849","4 years, 0 days"
3,14,Franklin Pierce (1804–1869),NaN,New Hampshire,"March 4, 1853","March 4, 1857","4 years, 0 days"
4,15,James Buchanan (1791–1868),NaN,Pennsylvania,"March 4, 1857","March 4, 1861","4 years, 0 days"
5,17,Andrew Johnson (1808–1875),NaN,Tennessee,"April 15, 1865[c]","March 4, 1869","3 years, 323 days"
6,22,Grover Cleveland (1837–1908),NaN,New York,"March 4, 1885","March 4, 1889","8 years, 0 days"
7,24,Grover Cleveland (1837–1908),NaN,New York,"March 4, 1893","March 4, 1897","8 years, 0 days"
8,28,Woodrow Wilson (1856–1924),NaN,New Jersey,"March 4, 1913","March 4, 1921","8 years, 0 days"
9,32,Franklin D. Roosevelt (1882–1945),NaN,New York,"March 4, 1933","April 12, 1945[d]","12 years, 39 days"
10,33,Harry S. Truman (1884–1972),NaN,Missouri,"April 12, 1945","January 20, 1953","7 years, 283 days"
11,35,John F. Kennedy (1917–1963),NaN,Massachusetts,"January 20, 1961","November 22, 1963[d]","2 years, 306 days"
12,36,Lyndon B. Johnson (1908–1973),NaN,Texas,"November 22, 1963","January 20, 1969","5 years, 59 days"
13,39,Jimmy Carter (born 1924),NaN,Georgia,"January 20, 1977","January 20, 1981","4 years, 0 days"
14,42,Bill Clinton (born 1946),NaN,Arkansas,"January 20, 1993","January 20, 2001","8 years, 0 days"
15,44,Barack Obama (born 1961),NaN,Illinois,"January 20, 2009","January 20, 2017","8 years, 0 days"
16,46,Joe Biden (born 1942),NaN,Delaware,"January 20, 2021",Incumbent,"3 years, 136 days"

In [35]:
df['Term start']=df['Term start'].str.replace("[c]","")

In [38]:
df['Term start']=df['Term start'].apply(lambda x: datetime.strptime(x, "%B %d, %Y"))

In [43]:
len(df[df['Term start'] > "1980-01-01"]["President"].unique().tolist())

3

In [88]:
df2=pd.read_html("https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States")[0]

In [91]:
df2

,No.[a],Portrait,Name (Birth–Death),Term[14],Party[b][15],Party[b][15].1,Election,Vice President[16]
0,1,NaN,George Washington (1732–1799) [17],"[April 30, 1789, March 4, 1797]",NaN,Unaffiliated,1788–1789 1792,John Adams[c]
1,2,NaN,John Adams (1735–1826) [19],"[March 4, 1797, March 4, 1801]",NaN,Federalist,1796,Thomas Jefferson[d]
2,3,NaN,Thomas Jefferson (1743–1826) [21],"[March 4, 1801, March 4, 1809]",NaN,Democratic- Republican,1800 1804,Aaron Burr George Clinton
3,4,NaN,James Madison (1751–1836) [22],"[March 4, 1809, March 4, 1817]",NaN,Democratic- Republican,1808 1812,"George Clinton[e] Vacant after April 20, 1812 ..."
4,5,NaN,James Monroe (1758–1831) [24],"[March 4, 1817, March 4, 1825]",NaN,Democratic- Republican,1816 1820,Daniel D. Tompkins
5,6,NaN,John Quincy Adams (1767–1848) [25],"[March 4, 1825, March 4, 1829]",NaN,Democratic- Republican[f] National Republican,1824,John C. Calhoun[g]
6,7,NaN,Andrew Jackson (1767–1845) [28],"[March 4, 1829, March 4, 1837]",NaN,Democratic,1828 1832,"John C. Calhoun[h] Vacant after December 28, 1..."
7,8,NaN,Martin Van Buren (1782–1862) [29],"[March 4, 1837, March 4, 1841]",NaN,Democratic,1836,Richard Mentor Johnson
8,9,NaN,William Henry Harrison (1773–1841) [30],"[March 4, 1841, April 4, 1841]",NaN,Whig,1840,John Tyler
9,10,NaN,John Tyler (1790–1862) [31],"[April 4, 1841, March 4, 1845]",NaN,Whig[j] Unaffiliated,–,Vacant throughout presidency
10,11,NaN,James K. Polk (1795–1849) [34],"[March 4, 1845, March 4, 1849]",NaN,Democratic,1844,George M. Dallas
11,12,NaN,Zachary Taylor (1784–1850) [35],"[March 4, 1849, July 9, 1850]",NaN,Whig,1848,Millard Fillmore
12,13,NaN,Millard Fillmore (1800–1874) [36],"[July 9, 1850, March 4, 1853]",NaN,Whig,–,Vacant throughout presidency
13,14,NaN,Franklin Pierce (1804–1869) [38],"[March 4, 1853, March 4, 1857]",NaN,Democratic,1852,"William R. King[e] Vacant after April 18, 1853"
14,15,NaN,James Buchanan (1791–1868) [39],"[March 4, 1857, March 4, 1861]",NaN,Democratic,1856,John C. Breckinridge
15,16,NaN,Abraham Lincoln (1809–1865) [40],"[March 4, 1861, April 15, 1865]",NaN,Republican National Union[l],1860 1864,Hannibal Hamlin Andrew Johnson
16,17,NaN,Andrew Johnson (1808–1875) [42],"[April 15, 1865, March 4, 1869]",NaN,National Union[n] Democratic,–,Vacant throughout presidency
17,18,NaN,Ulysses S. Grant (1822–1885) [43],"[March 4, 1869, March 4, 1877]",NaN,Republican,1868 1872,Schuyler Colfax Henry Wilson[e] Vacant after N...
18,19,NaN,Rutherford B. Hayes (1822–1893) [44],"[March 4, 1877, March 4, 1881]",NaN,Republican,1876,William A. Wheeler
19,20,NaN,James A. Garfield (1831–1881) [45],"[March 4, 1881, September 19, 1881]",NaN,Republican,1880,Chester A. Arthur
20,21,NaN,Chester A. Arthur (1829–1886) [46],"[September 19, 1881, March 4, 1885]",NaN,Republican,–,Vacant throughout presidency
21,22,NaN,Grover Cleveland (1837–1908) [48],"[March 4, 1885, March 4, 1889]",NaN,Democratic,1884,Thomas A. Hendricks[e] Vacant after November 2...
22,23,NaN,Benjamin Harrison (1833–1901) [49],"[March 4, 1889, March 4, 1893]",NaN,Republican,1888,Levi P. Morton
23,24,NaN,Grover Cleveland (1837–1908) [48],"[March 4, 1893, March 4, 1897]",NaN,Democratic,1892,Adlai Stevenson I
24,25,NaN,William McKinley (1843–1901) [50],"[March 4, 1897, September 14, 1901]",NaN,Republican,1896 1900,"Garret Hobart[e] Vacant after November 21, 189..."
25,26,NaN,Theodore Roosevelt (1858–1919) [51],"[September 14, 1901, March 4, 1909]",NaN,Republican,– 1904,"Vacant through March 4, 1905 Charles W. Fairbanks"
26,27,NaN,William Howard Taft (1857–1930) [53],"[March 4, 1909, March 4, 1913]",NaN,Republican,1908,"James S. Sherman[e] Vacant after October 30, 1912"
27,28,NaN,Woodrow Wilson (1856–1924) [54],"[March 4, 1913, March 4, 1921]",NaN,Democratic,1912 1916,Thomas R. Marshall
28,29,NaN,Warren G. Harding (1865–1923) [55],"[March 4, 1921, August 2, 1923]",NaN,Republican,1920,Calvin Coolidge
29,30,NaN,Calvin Coolidge (1872–1933) [56],"[August 2, 1923, March 4, 1929]",NaN,Republican,– 1924,"Vacant through March 4, 1925 Charles G. Dawes"
30,31,NaN,Herbert Hoover (1874–1964) [58],"[March 4, 1929, March 4, 1933]",NaN,Republican,1928,Charles Curtis
31,32,NaN,Franklin D. Roosevelt (1882–1945) [59],"[March 4, 1933, April 12, 1945]",NaN,Democratic,1932 1936 1940 1944,John Nance Garner Henry A. Wallace Harry S. Tr...
32,33,NaN,Harry S. Truman (1884–1972) [60],"[April 12, 1945, January 20, 1953]",NaN,Democratic,– 1948,"Vacant through January 20, 1949 Alben W. Barkley"
33,34,NaN,Dwight D. Eisenhower (1890–1969) [62],"[January 20, 1953, January 20, 1961]",NaN,Republican,1952 1956,Richard Nixon
34,35,NaN,John F. Kennedy (1917–1963) [63],"[January 20, 1961, November 22, 1963]",NaN,Democratic,1960,Lyndon B. Johnson
35,36,NaN,Lyndon B. Johnson (1908–1973) [64],"[November 22, 1963, January 20, 1969]",NaN,Democratic,– 1964,"Vacant through January 20, 1965 Hubert Humphrey"
36,37,NaN,Richard Nixon (1913–1994) [66],"[January 20, 1969, August 9, 1974]",NaN,Republican,1968 1972,Spiro Agnew[h] Vacant: October 10 – December 6...
37,38,NaN,Gerald Ford (1913–2006) [67],"[August 9, 1974, January 20, 1977]",NaN,Republican,–,"Vacant through December 19, 1974 Nelson Rockef..."
38,39,NaN,Jimmy Carter (b. 1924) [68],"[January 20, 1977, January 20, 1981]",NaN,Democratic,1976,Walter Mondale
39,40,NaN,Ronald Reagan (1911–2004) [69],"[January 20, 1981, January 20, 1989]",NaN,Republican,1980 1984,George H. W. Bush
40,41,NaN,George H. W. Bush (1924–2018) [70],"[January 20, 1989, January 20, 1993]",NaN,Republican,1988,Dan Quayle
41,42,NaN,Bill Clinton (b. 1946) [71],"[January 20, 1993, January 20, 2001]",NaN,Democratic,1992 1996,Al Gore
42,43,NaN,George W. Bush (b. 1946) [72],"[January 20, 2001, January 20, 2009]",NaN,Republican,2000 2004,Dick Cheney
43,44,NaN,Barack Obama (b. 1961) [73],"[January 20, 2009, January 20, 2017]",NaN,Democratic,2008 2012,Joe Biden
44,45,NaN,Donald Trump (b. 1946) [74],"[January 20, 2017, January 20, 2021]",NaN,Republican,2016,Mike Pence
45,46,NaN,Joe Biden (b. 1942) [13],"[January 20, 2021, June 05, 2024]",NaN,Democratic,2020,Kamala Harris

In [89]:
df2['Term[14]']=df2['Term[14]'].str.replace("Incumbent", datetime.now().strftime("%B %d, %Y"))

In [66]:
import re

In [90]:

date_pattern = r"([A-Za-z]+ \d{1,2}, \d{4})"

df2['Term[14]']=df2['Term[14]'].apply(lambda x: re.findall(date_pattern, x))

In [103]:
date_format = "%B %d, %Y"


for date_range in df2['Term[14]']:
    
    start_date_str, end_date_str = date_range
    
    start_date = datetime.strptime(start_date_str, date_format).date()
    end_date = datetime.strptime(end_date_str, date_format).date()

    their_birthday="2010-01-01"
 
    their_birthday = datetime.strptime(their_birthday, "%Y-%m-%d").date()

    if start_date <= their_birthday <= end_date:
        a=df2[df2['Term[14]'].isin([date_range])]['Name (Birth–Death)']
        pattern = r"(\(\d{1,4}–\d{1,4}\)|\[\d+\])"
        print(re.sub(pattern, '',a).strip())

        
    else:
        pass

TypeError: expected string or bytes-like object

In [101]:
pattern = r"(\(\d{1,4}–\d{1,4}\)|\[\d+\])"


re.sub(pattern, '', "Warren G. Harding (1865–1923) [55]").strip()

'Warren G. Harding'

In [107]:
correct_birthday = datetime.strptime("2010-01-01", "%Y-%m-%d").date()

# Apply date_pattern to df2['Term[14]'] to extract dates
df2['Term[14]'] = df2['Term[14]'].apply(lambda x: re.findall(date_pattern, ' '.join(x)))

# Iterate over each date range in df2['Term[14]']
for date_range in df2['Term[14]']:
    start_date_str, end_date_str = date_range
    
    # Parse start and end dates
    start_date = datetime.strptime(start_date_str, date_format).date()
    end_date = datetime.strptime(end_date_str, date_format).date()
    
    # Check if the correct_birthday falls within the date range
    if start_date <= correct_birthday <= end_date:
        # Filter rows based on the date_range
        filtered_rows = df2[df2['Term[14]'].apply(lambda x: x == date_range)]
        
        # Extract the name from the corresponding row
        name = filtered_rows['Name (Birth–Death)'].iloc[0]
        
        # Remove anything starting with '('
        name_without_parentheses = re.sub(r"\(.*", "", name)
        
        # Print the cleaned name
        print(name_without_parentheses.strip())

Barack Obama

In [61]:
df[df['Term start'] > their_birthday]

,#,President,Portrait,State,Term start,Term end,Years in office
14,42,Bill Clinton (born 1946),NaN,Arkansas,1993-01-20,"January 20, 2001","8 years, 0 days"
15,44,Barack Obama (born 1961),NaN,Illinois,2009-01-20,"January 20, 2017","8 years, 0 days"
16,46,Joe Biden (born 1942),NaN,Delaware,2021-01-20,Incumbent,"3 years, 136 days"

In [111]:
birth="2025-10-10"
if birth>datetime.now().strftime("%Y-%m-%d"):
    print(1)

1

In [114]:
numbers=[22, 90, 0, -10, 3, 22,48]

print(numbers.sort())

None

In [117]:
sorted(numbers)[-2]

48

In [119]:
import statistics

In [120]:
statistics.mean(numbers)

25

In [121]:
statistics.median(numbers)

22

In [123]:
import statistics
mean_num=statistics.mean(numbers)
median_num=statistics.median(numbers)

if mean_num==median_num:
    print("The mean and the median are equal")
elif mean_num>median_num:
    print("The mean is higher")
elif median>mean_num:
    print("The median is higher")

The mean is higher

In [124]:
movie={"title":"Interstellar","year":"2014","director":"Christopher Nolan"}
print("My favorite movie is", movie['title'], "which was released in", movie['year'], "and was directed by", movie['director'])

My favorite movie is Interstellar which was released in 2014 and was directed by Christopher Nolan

In [126]:
movie={"title":"Interstellar","year":"2014","director":"Christopher Nolan"}
print("My favorite movie is", movie['title'], "which was released in", movie['year'], "and was directed by", movie['director'])

movie["budget"]="165000000"
movie["revenue"]="733202212"
print(movie["budget"])
print(movie["revenue"])

My favorite movie is Interstellar which was released in 2014 and was directed by Christopher Nolan
165000000
733202212

In [127]:
movie["budget"]=int("165000000")
movie["revenue"]=int("733202212")
print(movie["budget"])
print(movie["revenue"])

165000000
733202212

In [128]:
area_stats=[{"area":"NYC. Manhattan","population":int(1600000)},{"area":"Brooklyn","population":int(2600000)},
            {"area":"Bronx","population":int(1400000)},{"area":"Queens",
            "population":int(2300000)},{"area":"Staten Island","population":int(470000)
            }]

In [134]:
area_stats.keys()

AttributeError: 'list' object has no attribute 'keys'

In [138]:
populations=int(0)
for population in area_stats:
    populations=populations+int(population)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

In [144]:
print(int(numbers[1])+int(numbers)[3])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [145]:
int((numbers)[1])

0

In [146]:
countries=["USA","China","Japan","Germany","France","Netherlands","Greece"]

#2
for country in countries:
    print(country)

#3
countries=sorted(countries)
print(countries)

#4
print(countries)[0])

USA
China
Japan
Germany
France
Netherlands
Greece
['China', 'France', 'Germany', 'Greece', 'Japan', 'Netherlands', 'USA']
['China', 'France', 'Germany', 'Greece', 'Japan', 'Netherlands', 'USA']

TypeError: 'NoneType' object is not subscriptable